### ISSUE TITLE
dkms autoinstall not working

### ISSUE THREAD

**Issue by michieltimmerman** [dell/thunderbolt-icm-dkms#4]
```
dkms autoinstall
```
```
Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -C ./ KVER=4.9.28-1-lts...(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.9.28-1-lts (x86_64)
Consult /var/lib/dkms/thunderbolt-icm-dkms/r8.c2ec86c/build/make.log for more information.
```

```
cat /var/lib/dkms/thunderbolt-icm-dkms/r8.c2ec86c/build/make.log
```
```
DKMS make.log for thunderbolt-icm-dkms-r8.c2ec86c for kernel 4.9.28-1-lts (x86_64)
Wed May 17 18:09:35 CEST 2017
make: Entering directory '/var/lib/dkms/thunderbolt-icm-dkms/r8.c2ec86c/build'
make -C /lib/modules/4.9.28-1-lts/build M=`pwd` modules
make[1]: Entering directory '/usr/lib/modules/4.9.28-1-lts/build'
  CC [M]  /var/lib/dkms/thunderbolt-icm-dkms/r8.c2ec86c/build/icm_nhi.o
  CC [M]  /var/lib/dkms/thunderbolt-icm-dkms/r8.c2ec86c/build/net.o
/var/lib/dkms/thunderbolt-icm-dkms/r8.c2ec86c/build/net.c: In function ‘tbt_net_alloc_mapped_page’:
/var/lib/dkms/thunderbolt-icm-dkms/r8.c2ec86c/build/net.c:478:14: error: implicit declaration of function ‘dma_map_page_attrs’ [-Werror=implicit-function-declaration]
   buf->dma = dma_map_page_attrs(dev, buf->page, 0, PAGE_SIZE,
              ^~~~~~~~~~~~~~~~~~
/var/lib/dkms/thunderbolt-icm-dkms/r8.c2ec86c/build/net.c: In function ‘tbt_net_poll’:
/var/lib/dkms/thunderbolt-icm-dkms/r8.c2ec86c/build/net.c:810:5: error: implicit declaration of function ‘dma_unmap_page_attrs’ [-Werror=implicit-function-declaration]
     dma_unmap_page_attrs(&port->nhi_ctxt->pdev->dev,
     ^~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/thunderbolt-icm-dkms/r8.c2ec86c/build/net.c: In function ‘nhi_alloc_etherdev’:
/var/lib/dkms/thunderbolt-icm-dkms/r8.c2ec86c/build/net.c:2259:9: error: ‘struct net_device’ has no member named ‘min_mtu’
  net_dev->min_mtu = ETH_MIN_MTU;
         ^~
/var/lib/dkms/thunderbolt-icm-dkms/r8.c2ec86c/build/net.c:2259:21: error: ‘ETH_MIN_MTU’ undeclared (first use in this function)
  net_dev->min_mtu = ETH_MIN_MTU;
                     ^~~~~~~~~~~
/var/lib/dkms/thunderbolt-icm-dkms/r8.c2ec86c/build/net.c:2259:21: note: each undeclared identifier is reported only once for each function it appears in
/var/lib/dkms/thunderbolt-icm-dkms/r8.c2ec86c/build/net.c:2260:9: error: ‘struct net_device’ has no member named ‘max_mtu’
  net_dev->max_mtu = TBT_NET_MTU - ETH_HLEN;
         ^~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:294: /var/lib/dkms/thunderbolt-icm-dkms/r8.c2ec86c/build/net.o] Error 1
make[1]: *** [Makefile:1490: _module_/var/lib/dkms/thunderbolt-icm-dkms/r8.c2ec86c/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.9.28-1-lts/build'
make: *** [Makefile:6: all] Error 2
make: Leaving directory '/var/lib/dkms/thunderbolt-icm-dkms/r8.c2ec86c/build'
```

**Comment by superm1** [comment]
I've imported the new upstream submission from today.  I verified it compiles against Linuses' tree.
https://github.com/dell/thunderbolt-icm-dkms/commit/0b3dabb7bcf9965957b32a19f4b03a46461577ce
