### ISSUE TITLE
Not working with new kernel

### ISSUE THREAD

**Issue by michieltimmerman** [dell/thunderbolt-icm-dkms#2]
```
% dkms autoinstall
Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -C ./ KVER=4.10.6-1-ARCH...(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.10.6-1-ARCH (x86_64)
Consult /var/lib/dkms/thunderbolt-icm-dkms/r2.2d1bd45/build/make.log for more information.
```
```
% cat /var/lib/dkms/thunderbolt-icm-dkms/r2.2d1bd45/build/make.log
DKMS make.log for thunderbolt-icm-dkms-r2.2d1bd45 for kernel 4.10.6-1-ARCH (x86_64)
Tue Mar 28 13:14:54 CEST 2017
make: Entering directory '/var/lib/dkms/thunderbolt-icm-dkms/r2.2d1bd45/build'
make -C /lib/modules/4.10.6-1-ARCH/build M=`pwd` modules
make[1]: Entering directory '/usr/lib/modules/4.10.6-1-ARCH/build'
  CC [M]  /var/lib/dkms/thunderbolt-icm-dkms/r2.2d1bd45/build/icm_nhi.o
/var/lib/dkms/thunderbolt-icm-dkms/r2.2d1bd45/build/icm_nhi.c:78:9: error: ‘GENL_ID_GENERATE’ undeclared here (not in a function)
  .id  = GENL_ID_GENERATE,
         ^~~~~~~~~~~~~~~~
/var/lib/dkms/thunderbolt-icm-dkms/r2.2d1bd45/build/icm_nhi.c: In function ‘icm_nhi_init’:
/var/lib/dkms/thunderbolt-icm-dkms/r2.2d1bd45/build/icm_nhi.c:1495:7: error: implicit declaration of function ‘genl_register_family_with_ops’ [-Werror=implicit-function-declaration]
  rc = genl_register_family_with_ops(&nhi_genl_family, nhi_ops);
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:295: /var/lib/dkms/thunderbolt-icm-dkms/r2.2d1bd45/build/icm_nhi.o] Error 1
make[1]: *** [Makefile:1490: _module_/var/lib/dkms/thunderbolt-icm-dkms/r2.2d1bd45/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.10.6-1-ARCH/build'
make: *** [Makefile:6: all] Error 2
make: Leaving directory '/var/lib/dkms/thunderbolt-icm-dkms/r2.2d1bd45/build'
```

**Comment by superm1** [comment]
This was reported in fwupd as well https://github.com/hughsie/fwupd/issues/103.  That means that the submission that Intel sent up in v9 is no longer valid.  Either they need to send up a new one, or someone needs to provide a patch to let it work on 4.10+.

You can report it here:
https://github.com/01org/thunderbolt-software-kernel-tree/issues

**Comment by Queuecumber** [comment]
Just a heads up, 4.12 (rc1) breaks the module again. I have a patch that fixes it (I think, haven't exhaustively tested it but it builds and installs OK) for me but probably we want to wait for intel to force-push again (which maybe they already have, I didnt bother looking)

For reference
```
diff --git a/thunderbolt-icm/net.c b/thunderbolt-icm/net.c
index 3ba8ac8..8d872ee 100644
--- a/thunderbolt-icm/net.c
+++ b/thunderbolt-icm/net.c
@@ -143,7 +143,7 @@ enum neg_event {
 };
 
 enum frame_status {
-       GOOD_FRAME,
+       GOOD_FRAME_ICM,
        GOOD_AS_FIRST_FRAME,
        GOOD_AS_FIRST_MULTICAST_FRAME,
        FRAME_NOT_READY,
@@ -615,7 +615,7 @@ static enum frame_status tbt_net_check_frame(struct tbt_port *port,
                        ++port->stats.rx_length_errors;
                        goto err;
                }
-               res = GOOD_FRAME;
+               res = GOOD_FRAME_ICM;
        } else { /* start of packet, validate the frame header */
                const u8 *addr;
```

**Comment by superm1** [comment]
Well this is making me start to wonder if patches should be carried in this DKMS package that apply for the various kernel versions.  Making sense of the various force pushes at Intel's repository to support latest kernel is going to be hard to track.

**Comment by Queuecumber** [comment]
Absolutely they are not making it easy. But I guess their goal is to get it merged into the kernel anyway, which is why I offered help there, the sooner that happens the less moving parts this setup has

**Comment by superm1** [comment]
I think it's probably a lost cause since [this ](https://lkml.org/lkml/2017/5/18/848)was submitted today.  The toolchain needs to be reworked to the sysfs interface that uses.

**Comment by superm1** [comment]
Alright, so i've redone it based upon that submission.  To be determined how well this works on older kernels, but it does compile against 4.11 fine for me.

**Comment by Queuecumber** [comment]
That updated patch is definitely how things should have been handled from the start, let's hope that it gets merged
